Feat/services page
computacao-ufcg/eureca-frontend pull request #256
Opened 2021-11-10 18:32 UTC by ielepassos

- design inicial da tela de serviços adicionado 
- botões do da header adicionados (mas o OnClick ainda não funciona como o esperado)

2021-11-15 16:54 UTC, jonatas-lima requested changes

2021-11-15 16:54 UTC, jonatas-lima commented on src/pages/services/index.jsx
> +        electivePriorityList || "^$"
acho que isso vai dar errado, porque esse endpoint não usa regex. o certo seria enviar nada ao invés de "^$" (nem a query 'electivePriorityList=...' seria enviada)

2021-11-18 03:51 UTC, ielepassos commented on src/pages/services/index.jsx
> +        electivePriorityList || "^$"
Dessa forma está funcionando, mas acredito que dê para fazer sem regex também ( como em numCredits, por exemplo)

2021-11-18 03:51 UTC, ielepassos commented
- removi o select do botão, já que a atualização do estado não estava ocorrendo de forma correta
- merge com a branch de comunicações

2021-11-21 19:58 UTC, ielepassos commented
- adequação com a nova versão da branch develop do backend
- adiciona tabela com as sugestões de matrícula

2021-11-29 01:38 UTC, merged