BugFix + ortografia
computacao-ufcg/eureca-frontend pull request #55
Opened 2020-10-30 01:17 UTC by herculesra

- Correção do bug encontrado por Ekarani. Solução: Paginação na tabela.
- Correção ortográfica para os labels do csv de ativos.
- Refatoração: 
     - Novo componente TableActives.
     - Limpeza de linhas desnecessárias.

2020-10-30 01:23 UTC, fubica requested changes

2020-10-30 01:23 UTC, fubica commented on src/components/StatisticsComponents/ativos/TableActives/index.jsx
> +                    <Table.HeaderCell>Periodo de Ingresso</Table.HeaderCell>
Período

2020-11-01 13:05 UTC, matheusarauj approved these changes

2020-11-02 13:45 UTC, matheusarauj approved these changes

2020-11-02 13:45 UTC, merged