Iele/alumni card home
computacao-ufcg/eureca-frontend pull request #88
Opened 2021-02-14 19:22 UTC by ielepassos

- Card do Alumni adicionado na homepage, sem as estatísticas, mas com os botões de navegação para as páginas 'ver mais' e 'atualizar dados' estilizados e funcionando.

- Labels da tabela de Empregadores modificados.

2021-02-14 19:30 UTC, herculesra requested changes
Os valores tem que ser em inglês. 
Ex.:
"value": private_company.

2021-02-14 19:35 UTC, herculesra requested changes
A requisição estava correta. Não precisa utilizar o "then" para tratar a promise.

2021-02-14 21:03 UTC, herculesra approved these changes

2021-02-15 18:36 UTC, ielepassos commented
- Tradução dos valores no util.js
- Nova rota do backend implementada na tabela de Ver Mais
- Correção das dataKeys das tabelas ( de 'fullName' para 'name')

2021-02-18 12:09 UTC, merged